name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run mkpkg
      run: ./src/mkpkg tasmotapm
    - name: Upload txz
      uses: actions/upload-artifact@v2
      with:
        path: ./archive/test.txz
